platform :ios, '13.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
            config.build_settings['SWIFT_VERSION'] = '5.1'
        end
    end
end